apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config
  namespace: alpes
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  # Pulsar dentro del clúster
  PULSAR_BINARY_URL: "pulsar://pulsar:6650"
  PULSAR_HTTP_URL: "http://pulsar:8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config-alpespartner
  namespace: alpes
data:
  START_CONSUMERS: "1"
  ALPESPARTNERS_ADDRESS: "alpespartner"
  PULSAR_ADDRESS: "broker"
  BROKER_HOST: "broker"
  DB_URL: "postgresql+psycopg2://admin:admin10100101.@postgres-core:5432/alpespartners_core"
  DATABASE_URL: "postgresql+psycopg2://admin:admin10100101.@postgres-core:5432/alpespartners_core"
  PULSAR_BROKER_URL: "pulsar://broker:6650"
  TOPIC_COMANDOS_CAMPANIAS: "persistent://public/default/comandos.campanias"
  TOPIC_EVENTOS_CAMPANIAS: "persistent://public/default/eventos.campanias"
  PULSAR_CONNECT_ATTEMPTS: "30"
  PULSAR_CONNECT_DELAY: "1"
  PULSAR_PRODUCER_ATTEMPTS: "10"
  PULSAR_PRODUCER_DELAY: "1"
  PULSAR_SEND_ATTEMPTS: "5"
  PULSAR_SEND_DELAY: "0.5"
  PYTHONPATH: "/src"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config-campanias
  namespace: alpes
data:
  SERVICE_MODULE: "campanias"
  PORT: "5000"
  PULSAR_BROKER_URL: "pulsar://broker:6650"
  START_CONSUMERS: "1"
  DB_URL: "postgresql+psycopg2://campanias_user:campanias_pass@postgres-campanias:5432/campanias_db"
  CORE_DB_URL: "postgresql+psycopg2://alpespartner_user:alpespartner_pass@postgres-alpespartner:5432/alpespartner_db"
  TOPIC_EVENTOS_CAMPANIAS: "persistent://public/default/eventos.campanias"
  TOPIC_COMANDOS_CAMPANIAS: "persistent://public/default/comandos.campanias"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/src"
  PULSAR_CONNECT_ATTEMPTS: "30"
  PULSAR_CONNECT_DELAY: "1"
  PULSAR_PRODUCER_ATTEMPTS: "10"
  PULSAR_PRODUCER_DELAY: "1"
  PULSAR_SEND_ATTEMPTS: "5"
  PULSAR_SEND_DELAY: "0.5"
  DB_HOST: "postgres-campanias"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config-cliente
  namespace: alpes
data:
  SERVICE_MODULE: "cliente"
  PORT: "5000"
  PULSAR_BROKER_URL: "pulsar://broker:6650"
  DB_URL: "postgresql+psycopg2://cliente_user:cliente_pass@postgres-cliente:5432/cliente_db"
  CORE_DB_URL: "postgresql+psycopg2://alpespartner_user:alpespartner_pass@postgres-alpespartner:5432/alpespartner_db"
  TOPIC_EVENTOS_CLIENTE: "persistent://public/default/eventos.cliente"
  TOPIC_COMANDOS_CLIENTE: "persistent://public/default/comandos.cliente"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/src"
  PULSAR_CONNECT_ATTEMPTS: "30"
  PULSAR_CONNECT_DELAY: "1"
  PULSAR_PRODUCER_ATTEMPTS: "10"
  PULSAR_PRODUCER_DELAY: "1"
  PULSAR_SEND_ATTEMPTS: "5"
  PULSAR_SEND_DELAY: "0.5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config-pagos
  namespace: alpes
data:
  SERVICE_MODULE: "pagos"
  PORT: "5000"
  PULSAR_BROKER_URL: "pulsar://broker:6650"
  DB_URL: "postgresql+psycopg2://pagos_user:pagos_pass@postgres-pagos:5432/pagos_db"
  CORE_DB_URL: "postgresql+psycopg2://alpespartner_user:alpespartner_pass@postgres-alpespartner:5432/alpespartner_db"
  TOPIC_EVENTOS_PAGOS: "persistent://public/default/eventos.pagos"
  TOPIC_COMANDOS_PAGOS: "persistent://public/default/comandos.pagos"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/src"
  PULSAR_CONNECT_ATTEMPTS: "30"
  PULSAR_CONNECT_DELAY: "1"
  PULSAR_PRODUCER_ATTEMPTS: "10"
  PULSAR_PRODUCER_DELAY: "1"
  PULSAR_SEND_ATTEMPTS: "5"
  PULSAR_SEND_DELAY: "0.5"
  DB_HOST: "postgres-pagos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alpes-config-bff
  namespace: alpes
data:
  SERVICE_MODULE: "bff"
  CAMPANIAS_SERVICE_URL: "http://campanias:5000"
  CLIENTE_SERVICE_URL: "http://cliente:5000"
  PAGOS_SERVICE_URL: "http://pagos:5000"
  CORE_SERVICE_URL: "http://alpespartner:5000"
  BFF_HOST: "0.0.0.0"
  BFF_PORT: "8000"
  BFF_DEBUG: "false"
  BFF_REQUEST_TIMEOUT: "30"
  BFF_MAX_RETRIES: "3"
  BFF_RETRY_DELAY: "1"
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/app/src"  
  DB_HOST: "postgres-campanias"