# pulsar.yaml (mínimo)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  namespace: alpes
spec:
  replicas: 1
  selector:
    matchLabels: { app: pulsar }
  template:
    metadata:
      labels: { app: pulsar }
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar:latest
          command: ["/bin/bash","-c"]
          args: ["bin/pulsar standalone -nss"]
          ports:
            - containerPort: 6650
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: alpes
spec:
  type: ClusterIP
  selector:
    app: pulsar
  ports:
    - name: pulsar
      port: 6650
      targetPort: 6650
    - name: http
      port: 8080
      targetPort: 8080


