name: Build and Publish Postgres Image

on:
  workflow_dispatch:
  push:
    branches:
      - feature/postgres-image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST || 'ghcr.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: docker/postgres/Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_HOST || 'ghcr.io' }}/${{ secrets.REGISTRY_USERNAME }}/alpespartners-postgres:latest
